devsapp/fc

- package.json
- publish.yaml
> docs: update version

- publish.yaml
change provider to 阿里云 in publish.yml
> docs: change provider in publish.yml

- examples/code-local/s.yaml
- package.json
- publish.yaml
change component name from fc-domain to fc
> docs: change component name

- src/index.ts
- src/lib/tarnsform-nas.ts
nas 执行指令异常 common 'ls -al' 报错不符合预期 #44
> fix: nas command error

- docs/Usage/metrics.md
- src/lib/static.ts
> fix: metrcis => metrics

- package.json
- src/common/base.ts
- src/index.ts
- src/lib/tarnsform-nas.ts
> feat: nas option update

- docs/Usage/alias.md
- docs/Usage/layer.md
- docs/Usage/onDemand.md
- docs/Usage/provision.md
- docs/Usage/version.md
> docs: update command docs

- src/lib/component/alias.ts
- src/lib/component/on-demand.ts
- src/lib/component/provision.ts
- src/lib/component/remove.ts
- src/lib/component/version.ts
- src/lib/tarnsform-nas.ts
- src/lib/utils.ts
> fix: cli not fount credential

- docs/Usage/alias.md
- docs/Usage/layer.md
- docs/Usage/version.md
- src/command/alias.ts
- src/command/layer.ts
- src/command/version.ts
- src/lib/component/alias.ts
- src/lib/component/on-demand.ts
- src/lib/component/provision.ts
- src/lib/component/remove.ts
- src/lib/component/version.ts
- src/lib/help/remove.ts
- 修复参数 version 为系统参数，修改为 version-id
> fix: version update version-id

- src/index.ts
- src/lib/client.ts
- src/lib/component/alias.ts
- src/lib/component/on-demand.ts
- src/lib/component/provision.ts
- src/lib/component/remove.ts
- src/lib/component/version.ts
> feat: add support fc endpoint

- examples/layer/.fcignore
- examples/layer/code/index.js
- examples/layer/code/package.json
- examples/layer/readme.md
- examples/layer/s.yaml
- package.json
> example: layer

- examples/custom-domain/s.yaml
- examples/fun2s/template.yaml
- package.json
- publish.yaml
- src/command/fun2s.ts
- src/index.ts
- src/lib/tarnsform-nas.ts
https://github.com/devsapp/fc/issues/228
> feat: support fun2s

- docs/Usage/remote.md
- src/command/remote.ts
- src/index.ts
- src/lib/component/fc-remote-debug.ts
- Add fc-remote-debug component
> feat: remote debug

- docs/Getting-started/Install-tutorial.md
> fix docker-install.md

- docs/Others/fun-fc.md
更新了fun的yml转s的yaml相关指令说明
https://github.com/devsapp/fc/issues/266
> update: /docs/others/fun-fc.md

- doc/doc.json
- docs/Usage/deploy.md
- src/lib/help/build.ts
- src/lib/help/deploy.ts
Replace ''If executing s deploy is equivalent to s deploy all" with "Executing `s deploy` is equivalent to `s deploy all`"
> Fix grammar

- src/lib/interface/vpc.ts
- src/lib/transform-nas.ts
https://github.com/devsapp/fc/issues/295
> fix: vswitchIds to vSwitchIds

- src/index.ts
不能执行 s nas command ls -lh /mnt/auto 指令 https://github.com/devsapp/fc/issues/394
> fix: invoke ls -lh /mnt/auto error

- .github/workflows/ci.yaml
- test/deploy-integration.test.ts
- test/mock-data.ts
- test/test-utils.ts
经过梳理发现每次报错都是重复操作 auto 的生成的 vpc、nas 导致。
不删除资源：vpcConfig 、nasConfig、sls 的 project 和  AliyunFCDefaultRole(ram)，其他的资源非公有的资源都需要清除
> ci: fix faild

- src/index.ts
Fix https://github.com/devsapp/fc/issues/420
> Refactor: remove unused stdout

- .github/workflows/ci.yaml
https://stackoverflow.com/questions/59356518/retry-failed-jobs-in-github-actions
> add retry test-integration  once in ci

- docs/command/local.md
> docs: update docs of local invoke

- docs/command/proxied.md
> docs: update docs of proxied invoke

- docs/command/stress.md
1. 权限部分需要 @wss-git 帮忙 review 一下
>  docs: update docs of stress

- docs/zh/command/metrics.md
> Feat: update metrics.md

- src/index.ts
- 新增 domain 的配置查看 https://github.com/devsapp/fc/issues/575
> add info domain config

- src/index.ts
> fix: s evel start -h not show help

- src/lib/help/invoke.ts
https://github.com/devsapp/fc/issues/605
> add invoke function example

- docs/en/command/invoke.md
- docs/zh/command/invoke.md
- src/lib/component/remove.ts
- src/lib/help/invoke.ts
- invoke help
- plan CatchableError 不被过滤
> fix: CatchableError not reveal all the details

- docs/en/command/layer.md
- docs/en/yaml/customDomains.md
- docs/zh/command/layer.md
- docs/zh/yaml/customDomains.md
- publish.yaml
- src/index.ts
- src/lib/component/provision.ts
- src/lib/component/remove.ts
- src/lib/help/layer.ts
fix: 使用 s provision list， 参数 --qualifier 指定为LATEST，无法正常显示 #693 
s remove 删除时删除 domain
支持 tslConfig
支持 layer download
> fix: provision list support designated LATEST

- docs/zh/yaml/customDomains.md
> docs: update customDomains.md

- docs/zh/tips.md
> update ignore docs

- docs/en/tips.md
- docs/zh/tips.md
> docs: fc-domain 组件使用示例

- package.json
- src/entry-public-method/index.ts
- src/entry-public-method/tip-layer-arn.ts
- src/lib/interface/fc/function.ts
https://github.com/devsapp/fc/issues/824
> feat: support layerArnV2

- src/index.ts
https://github.com/devsapp/fc/issues/845
> fix: stress start http function need url

- docs/en/yaml/function.md
- docs/zh/yaml/function.md
Ref https://github.com/devsapp/fc-deploy/pull/184/files
> update function doc

- docs/zh/yaml/service.md
Ref: https://github.com/devsapp/fc/issues/847
> service: add desc for ossMountConfig

- src/entry-public-method/index.ts
https://github.com/devsapp/fc/issues/876
> custom domain qualifier need to string

- src/index.ts
Fix: https://github.com/devsapp/fc/issues/870
> fix: deploy error return undefined

- docs/en/tips.md
- docs/en/yaml/readme.md
- docs/zh/tips.md
- docs/zh/yaml/readme.md
Fix: https://github.com/devsapp/fc/issues/875
> fix: custom domain docs link

- docs/zh/yaml/service.md
- publish.yaml
> docs: update ossMountConfig docs

- docs/zh/yaml/function.md
- docs/zh/yaml/readme.md
- publish.yaml
> docs: update docs

- docs/zh/yaml/function.md
> fix: docs runtime docs

- docs/zh/yaml/function.md
- publish.yaml
> feat: support instanceSoftConcurrency

- docs/en/yaml/readme.md
- docs/zh/yaml/readme.md
- docs/zh/yaml/service.md
> docs: update vpcbinding doc

- docs/en/yaml/readme.md
- docs/en/yaml/triggers.md
- docs/zh/yaml/readme.md
- docs/zh/yaml/triggers.md
> docs: add disableURLInternet

- src/entry-public-method/check.ts
- src/entry-public-method/index.ts
https://github.com/devsapp/fc/issues/936
> fix: check service & function name

- docs/en/yaml/customDomains.md
- docs/zh/command/alias.md
- docs/zh/yaml/customDomains.md
- publish.yaml
- src/entry-public-method/index.ts
- src/index.ts
- src/lib/help/alias.ts
- src/lib/help/deploy.ts
https://github.com/devsapp/fc/issues/946
> docs: 📝 修改 deploy help 信息

- src/index.ts
Ref： https://github.com/devsapp/fc/issues/956
> feat: ✨ deploy function 支持输出 cup diskSize
